- repos/cli-utils/src/task/sharedOptions.js
- src/utils/docker/__tests__/getImageRef.js
- src/utils/docker/tags/__tests__/buildTags.js
- src/utils/getters/__tests__/getImgFrom.js
- src/utils/getters/__tests__/getImgNameContext.js
Fixing test refs to correct org
> fix(tests): Fix test refs to SV

- repos/args-parse/package.json
- repos/args-parse/yarn.lock
- repos/cli-utils/package.json
- repos/cli-utils/src/commands/__tests__/commands.js
- repos/cli-utils/src/commands/commands.js
- repos/cli-utils/src/commands/index.js
- repos/cli-utils/yarn.lock
> Updating cli-utils to version 6.3.2

- repos/git-lib/package.json
- repos/git-lib/yarn.lock
> Updating git-lib to version 0.0.2

- repos/git-lib/package.json
- repos/git-lib/yarn.lock
- repos/parse-config/package.json
- repos/parse-config/yarn.lock
> Updating parse-config to version 0.0.2

- repos/args-parse/yarn.lock
- repos/ask-it/yarn.lock
- repos/cli-utils/yarn.lock
- repos/git-lib/yarn.lock
- repos/mutagen-lib/yarn.lock
- repos/parse-config/yarn.lock
- repos/spawn-cmd/yarn.lock
- src/tasks/tap/print.js
- yarn.lock
> Sv develop

- keg
- package.json
- repos/mutagen-lib/yarn.lock
- src/tasks/docker/build.js
- src/tasks/docker/tunnel.js
- src/utils/docker/addBuildPlatform.js
- src/utils/docker/buildDockerCmd.js
- src/utils/docker/compose/buildComposeCmd.js
- src/utils/task/options/buildOptions.js
- yarn.lock
* Why was this ticket created?
* List the updates you made to the codebase. Use your best judgement on how detailed the description should be
* *Name of file modified*
* What changed in this file? Why?
* List out the steps you took to test your changes
* Use the template below for listing out your testing steps
```
* <Function> Testing:
* Step 1
* Step 2
* Step n
* Verify <some_expectations>
```
* (Example) Search Testing:
* login to zsales.zerista.com as admin
* Click on the 'Speakers' tab
* Search for 'billy bob'
* Verify that the speaker user shows up
> Docer build platform

- src/libs/docker/image.js
- src/tasks/docker/image/run.js
- src/utils/task/options/runOptions.js
* I needed to run an image with privileged set to true
* It currently doesn't exist as an option
* Add privileged option to docker run task
> feat(tasks:run): Add privileged option to docker run

- repos/parse-config/package.json
- repos/parse-config/src/__mocks__/.env.test
- repos/parse-config/src/__mocks__/parse.yml
- repos/parse-config/src/__mocks__/ymlHelpers.js
- repos/parse-config/src/loaders/__tests__/loadConfigs.js
- repos/parse-config/src/loaders/index.js
- repos/parse-config/src/loaders/loadConfigs.js
- repos/parse-config/src/utils/utils.js
- repos/parse-config/src/yml/yml.js
* Allows loading config for apps dynamically
> feat(loadConfigs): Add loadConfigs method

- repos/parse-config/package.json
* Merge published parse-config
> Updating tap to version 0.2.0

- repos/spawn-cmd/package.json
- repos/spawn-cmd/src/spawnCmd.js
* Return the spawned process from the promise
* Patch  version
> Updating tap to version 0.1.4

- repos/cli-utils/package.json
- repos/cli-utils/src/index.js
- repos/cli-utils/src/process/__tests__/addToProcess.js
- repos/cli-utils/src/process/__tests__/processExit.js
- repos/cli-utils/src/process/addToProcess.js
- repos/cli-utils/src/process/index.js
- repos/cli-utils/src/process/processExit.js
- repos/cli-utils/yarn.lock
- repos/git-lib/package.json
- repos/git-lib/yarn.lock
- repos/mutagen-lib/package.json
- repos/mutagen-lib/yarn.lock
- repos/parse-config/package.json
- repos/parse-config/yarn.lock
* Add a couple helpers
* Update spawn-cmd version
> Cli utils process helpers

- package.json
- src/utils/docker/compose/addComposeConfigs.js
* Add ability to load compose file from env if not set in the values file
> Load compose from env

- repos/cli-utils/package.json
- repos/cli-utils/src/constants/constants.js
* Does not always exist in a test context
* Add check it it exists before getting filename
> fix(cli-utils): Check if require.main exists

- repos/args-parse/package.json
* Update major version of args-parse
> fix(repos): Fix overwriting args-parse config

- package.json
- repos/cli-utils/package.json
- repos/cli-utils/yarn.lock
- yarn.lock
> Cutils 0.6.0 f867b88

- src/tasks/git/branch/branch.js
* Allow deleting multiple branches at once
* Update branch task to allow deleting multiple branches at once
> feat: add multi delete for git branches

- package.json
- repos/args-parse/package.json
- repos/args-parse/yarn.lock
- repos/ask-it/package.json
- repos/ask-it/yarn.lock
- repos/cli-utils/package.json
- repos/cli-utils/yarn.lock
- repos/docker-lib/package.json
- repos/docker-lib/yarn.lock
- repos/git-lib/package.json
- repos/git-lib/yarn.lock
- repos/mutagen-lib/package.json
- repos/mutagen-lib/yarn.lock
- repos/parse-config/package.json
- repos/parse-config/yarn.lock
- repos/spawn-cmd/package.json
- repos/spawn-cmd/yarn.lock
- yarn.lock
* Update internal packages to use latest
> fix: update packages

- repos/args-parse/package.json
- repos/ask-it/package.json
- repos/cli-utils/package.json
- repos/parse-config/package.json
- repos/spawn-cmd/package.json
> Updating tap to version 9.0.0

- repos/args-parse/src/args/findArg.js
- repos/parse-config/README.md
- repos/parse-config/package.json
- repos/parse-config/src/loadConfigs/loadConfigs.js
> feat(parse): Add mergeStrategy option

- repos/cli-utils/package.json
- src/tasks/global/validate.js
* Allow loading typescript
* Fix some issues with loading args-parse confic
> Cutils 0.8.0 alpha 852b9aa

- repos/args-parse/src/args/ensureArgs.js
- repos/args-parse/src/options/checkBoolValue.js
- repos/args-parse/src/options/checkValueType.js
- repos/cli-utils/src/process/addToProcess.js
- src/tasks/tap/publish.js
- src/utils/services/publishService.js
* Fix bug with args-parse
* Migrate repo to use pnpm
> switch to pnpm.

- pnpm-lock.yaml
- repos/cli-utils/package.json
* Update args-parse version in cli-utils
> chore: update args-parse

- repos/cli-utils/package.json
> Updating tap to version 0.9.0

- repos/parse-config/configs/jest.config.js
- repos/parse-config/package.json
- repos/parse-config/src/constants/__tests__/constants.js
- repos/parse-config/src/constants/constants.js
- repos/parse-config/src/constants/index.js
- repos/parse-config/src/env/__tests__/env.js
- repos/parse-config/src/env/env.js
- repos/parse-config/src/loadConfigs/loadConfigs.js
- repos/parse-config/src/template/__tests__/template.js
- repos/parse-config/src/template/template.js
- repos/parse-config/src/utils/__tests__/appRoot.js
- repos/parse-config/src/utils/__tests__/utils.js
- repos/parse-config/src/utils/appRoot.js
- repos/parse-config/src/utils/utils.js
- repos/parse-config/src/yml/__tests__/yml.js
> feat: remove parse-config deps on cli-utils
